CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    observacoes TEXT,
    criado_em TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'America/Sao_Paulo')
);

CREATE TABLE produtos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    marca VARCHAR(100),
    quantidade INTEGER DEFAULT 0
);

CREATE TABLE servicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    valor_base DECIMAL(10,2) NOT NULL
);

CREATE TABLE historico_clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cliente_id INTEGER NOT NULL,
    servico_id INTEGER,

    data_historico DATE DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'America/Sao_Paulo')::DATE),

    observacao TEXT,

    CONSTRAINT fk_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_servico
        FOREIGN KEY (servico_id)
        REFERENCES servicos(id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX ux_clientes_telefone_normalizado
    ON clientes ((regexp_replace(telefone, '[^0-9]', '', 'g')))
    WHERE telefone IS NOT NULL AND btrim(telefone) <> '';
