CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL
);

CREATE TABLE "clientes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "telefone" varchar(20),
  "observacoes" text,
  "criado_em" timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'America/Sao_Paulo')
);

CREATE TABLE "produtos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "descricao" text,
  "marca" varchar(100),
  "quantidade" integer
);

CREATE TABLE "servicos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "descricao" text,
  "valor_base" decimal(10,2)
);

CREATE TABLE "historico_clientes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" integer NOT NULL,
  "servico_id" integer,
  "data_historico" date DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'America/Sao_Paulo')::date),
  "observacao" text
);

ALTER TABLE "historico_clientes" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "historico_clientes" ADD FOREIGN KEY ("servico_id") REFERENCES "servicos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE UNIQUE INDEX "ux_clientes_telefone_normalizado"
  ON "clientes" ((regexp_replace("telefone", '[^0-9]', '', 'g')))
  WHERE "telefone" IS NOT NULL AND btrim("telefone") <> '';
